version: '3'
services:
  api:
    build:
      context: api
      dockerfile: dockerfile
    command: nodemon --inspect=0.0.0.0:9229 server.js
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      - PORT=80
      - MS1=http://ms1
      - MS2=http://ms2
  ms1:
    build:
      context: ms1
      dockerfile: dockerfile
    command: nodemon --inspect=0.0.0.0:9229 server.js
    ports:
      - "3000:80"
    expose:
      - "80"
    environment:
      - PORT=80
  ms2:
    build:
      context: ms2
      dockerfile: dockerfile
    command: nodemon --inspect=0.0.0.0:9229 server.js
    ports:
      - "3001:80"
    expose:
      - "80"
    environment:
      - PORT=80